### ISSUE TITLE
Potential Denial of Service vunerability

### ISSUE THREAD

**Issue by Ecno92** [pennersr/django-healthpoint#1]
Healthpoint does the health checks first before checking which user is doing the request. After doing the actual health checks it decides whether the results are allowed to be displayed to the user. 
When you are doing a request with a staff member or with the special Basic authentication credentials, you will see the results in the response. Otherwise you just get a status code.

The health checks itself can have some latency as checking connectivity to related services (database, object storage etc.) is a typical use case for this package.

When an attacker knows about the health check endpoint it could in theory create a DoS attack by calling the endpoint without any authentication at a high request rate. 

There are several ways how to deal with this problem. According to me introducing a single boolean setting to require basic authentication when basic authentication is configured should be sufficient.

Looking forward to feedback on how to handle this. :+1:

**Comment by pennersr** [comment]
A few thoughts:

- People often target the health endpoints using external uptime checkers, that typically try to access the endpoints from various places all over the world, possibly simultaneously. In this use case, having endpoints that take a like time in order to come up with a response is dangerous anyway.

- DDOS prevention / rate limitting is a concern that should be handled elsewhere (e.g. at the HTTP server config level). There, you could easily prevent the health endpoint from being DDOS'ed.

Having said that, in order for healthpoint not to become too opinionated on the matter, I think indeed a setting (`HEALTHPOINT_AUTH_REQUIRED = False`) would be the right thing to address this issue. Pull requests are welcome!
